Assigment 2
FacultadInformatica-LinkedData/Curso2021-2022-DataScience pull request #28
Opened 2021-10-05 15:22 UTC by RodrigoDuranAndres

2021-11-02 11:49 UTC, dgarijo requested changes
You need to improve assignment 4. Also, you are removing the original notebooks! I cannot merge until you undo that

2021-11-02 11:49 UTC, dgarijo commented on Assignment4/Rodrigo-c20c033/task06.py
> +!pip install rdflib
This will not work in Python. You need to comment out this line (the same applies for other tasks)

2021-11-02 11:49 UTC, dgarijo commented on Assignment4/Rodrigo-c20c033/task06.py
> +g.add((ns.Researcher, VCARD.Work, ns.University))
This is wrong.  You cannot add properties between classes. Properties define the data model. You may state their domain and range with classes, but not like this

2021-11-02 11:49 UTC, dgarijo commented on Assignment4/Rodrigo-c20c033/task07.py
> +      OPTIONAL{?Subclases RDFS:subClassOf '''+ f"<{clase}>"+'''}
While this may work, it is not the correct way of doing it.
You can add a statement directly in sparql to retrieve only subclasses of Person, and use that in a very similar manner you do here. Just not precalculating the classes first, which defeats the purpose.
something like: select ?i where{ ?i rdf:type ?class. ?class rdfs:subclassOf* ex:Person}

2021-11-02 11:49 UTC, dgarijo commented on Assignment4/Rodrigo-c20c033/task07.py
> +        initNs = {"RDFS": RDFS, "RDF":RDF}
You are separating this in 2 queries. It should be done with only one query

2021-12-14 09:27 UTC, ocorcho commented
Given all the errors identified, we will close this pull request, and you will have the opportunity to resubmit later all of the assignments, one by one, if you wish.

2021-12-14 09:27 UTC, closed without merging

2021-12-14 10:32 UTC, RodrigoDuranAndres commented
Good morning.

I changed my push and I added an answer to your request saying I have 
changed it. I was eliminating two notebooks that I shouldn't (dum error) 
and I changed that, and also I changed all the assignments that you 
write a comment about.
Did I make more mistakes?
What can I do next time to make you notice changes I made in the push?

Sorry, Rodrigo.

El 2021-12-14 10:27, Oscar Corcho escribió:
> Given all the errors identified, we will close this pull request, and
> you will have the opportunity to resubmit later all of the
> assignments, one by one, if you wish.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe
> [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or
> Android [4].
> 
> Links:
> ------
> [1] 
> https://github.com/FacultadInformatica-LinkedData/Curso2021-2022-DataScience/pull/28#issuecomment-993343297
> [2] 
> https://github.com/notifications/unsubscribe-auth/AVXKA742KHIF67RNZMC4TTTUQ4EZZANCNFSM5FL6AQYA
> [3] 
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&amp;mt=8&amp;pt=524675
> [4] 
> https://play.google.com/store/apps/details?id=com.github.android&amp;referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub

2021-12-14 10:34 UTC, ocorcho commented
Do a fresh pull request now. Before submitting, make sure that you fetch from the global repository, so as to make sure that you have the latest version and there are no errors.

2021-12-15 16:37 UTC, RodrigoDuranAndres commented on Assignment4/Rodrigo-c20c033/task07.py
> +        initNs = {"RDFS": RDFS, "RDF":RDF}
done