assig2
FacultadInformatica-LinkedData/Curso2021-2022-DataScience pull request #32
Opened 2021-10-11 11:13 UTC by xiyaa

2021-10-14 14:47 UTC, ocorcho commented
Todo bien, pero no puedes eliminar el README.md

2021-11-15 11:45 UTC, dgarijo requested changes
Please address the problems in task 7

2021-11-15 11:45 UTC, dgarijo commented on Assignment4/notebooks/task06.py
> +!pip install rdflib
This won't run in Python. You need to comment it out

2021-11-15 11:45 UTC, dgarijo commented on Assignment4/notebooks/task07.py
> +    ?Subject rdf:type <r>
Malformed query. You are asking for the URI <r>, which should not exist.

2021-11-15 11:45 UTC, dgarijo commented on Assignment4/notebooks/task07.py
> +    ?Subject ?prop ?val
Not correct, you need to extract the subclasses in the query itself

2021-11-19 12:41 UTC, xiyaa commented on Assignment4/notebooks/task07.py
> +    ?Subject ?prop ?val
ok

2021-12-14 09:28 UTC, ocorcho commented
Assignment 2 is ok. Now @dgarijo can check assignment on Python.

2021-12-14 14:00 UTC, dgarijo commented on Assignment4/xiyaa-c20c030/task07.py
> +  print(s)
This is not asked, as you are printing all individuals

2021-12-14 14:00 UTC, merged